# Generated by Django 6.0.5 on 2026-05-14 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_servermember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermember',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='servers.server'),
        ),
    ]
