from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_serverrole_servermember_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrole',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='hoist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='mentionable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='create_instant_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='kick_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='ban_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='manage_channels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='manage_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='manage_webhooks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='view_audit_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='view_channel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='send_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='send_tts_messages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='manage_messages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='embed_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='attach_files',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='read_message_history',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='mention_everyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='use_external_emojis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='add_reactions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='connect',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='speak',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='mute_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='deafen_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='move_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='use_voice_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='priority_speaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='request_to_speak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='change_nickname',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serverrole',
            name='manage_nicknames',
            field=models.BooleanField(default=False),
        ),
    ]
