# Generated by Django 6.0.5 on 2026-05-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_serverrole_discord_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverrole',
            name='can_manage_channels',
        ),
        migrations.RemoveField(
            model_name='serverrole',
            name='can_manage_roles',
        ),
        migrations.RemoveField(
            model_name='serverrole',
            name='can_send_messages',
        ),
        migrations.RemoveField(
            model_name='serverrole',
            name='can_view_server',
        ),
    ]
